### PR TITLE
Remove per-file licensing

### PR DESCRIPTION
**Pull request by shawndwells**

### CODE REVIEW

**Comment by isimluk** [comment]
Directionally, looks fine. I am just afraid we may need to remove the one in `./hack/` directory as well. And perhaps amend pieces of code that reference the `./hack/`

**Comment by isimluk** [comment]
🏓

**Review by isimluk — APPROVED** [review]

**Comment by redhatrises** [comment]
Question: Should we remove per-file licensing? Seems like it is a standard thing to do... and if crafted correctly... can be mapped back to the project license file.

**Comment by shawndwells** [comment]
Looks like this PR got lost

@redhatrises yes, per file should be dropped. A repo-wide LICENSE should be used.

**Pull request merged**
