### PR TITLE
Add RHT required bundle labels

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Review by isimluk — APPROVED** [review]

**Review by isimluk — CHANGES_REQUESTED** [review]
This file is created by `make bundle` we need to put this info some other place.

**Comment by redhatrises** [comment]
> This file is created by `make bundle` we need to put this info some other place.

So that this point, we can either disable overwriting of the bundle files, add another dockerfile, or some other idea that you have on handling this.

**Comment by isimluk** [comment]
👍 Let me figure this one out.

**Comment by isimluk** [comment]
> 👍 Let me figure this one out.

Would you believe it? There seems to be no way to achieve this with the operator-sdk.

https://github.com/operator-framework/operator-sdk/issues/5002

**Comment by isimluk** [comment]
What I have found however is a following excerpt from the documentation at https://sdk.operatorframework.io/docs/olm-integration/generation/#bundle-format

>  Important: bundle generation is supposed to be idempotent, so any changes to
>  CSV fields able to be persisted (marked (user) or (marker) below) must be made
>  to the base set of manifests, typically found in config/.
>
>  Bundle metadata in bundle/metadata/annotations.yaml contains information about
>  a particular Operator version available in a registry. OLM uses this
>  information to install specific Operator versions and resolve dependencies.
>  That file and bundle.Dockerfile contain the same annotations, the latter as
>  LABELs, which do not need to be modified in most cases; if you do decide to
>  modify them, **both sets of annotations must be the same to ensure consistent Operator
>  deployment.**

Could you please amend `annotations.yaml` file together with `bundle.Dockerfile`? I will take care of the CI then.

**Comment by redhatrises** [comment]
Going to close this. Since operator-sdk overwrites the files, I believe a release script will be needed in the mean time.

**Pull request closed without merging**
