### PR TITLE
CRD pass falcon credentials to the operator

### PR DESCRIPTION
**Pull request by isimluk**
## Preview
Screenshot 2021-04-25 at 13 25 26

### CODE REVIEW

**Comment by redhatrises** [comment]
@isimluk can you rebase this against main?

**Comment by isimluk** [comment]
For sure. But please leave this on hold. I am investigating some (possible unrelated) issue.

**Comment by isimluk** [comment]
> For sure. But please leave this on hold. I am investigating some (possible unrelated) issue.

That unrelated issue is fixed in #17.

**Comment by isimluk** [comment]
> @isimluk can you rebase this against main?

@redhatrises, done.

**Comment by redhatrises** [comment]
LGTM

**Pull request merged**
