### PR TITLE
Update gcp-workload-identity.md

### PR DESCRIPTION
**Pull request by falcon-pioupiou**
fixing the service account used in the iam policy binding

### CODE REVIEW

**Comment by redhatrises** [comment]
I believe that the change should be made at https://github.com/CrowdStrike/falcon-operator/blob/main/apis/falcon/v1alpha1/falconcontainer_types.go#LL48C33-L48C40 to be `crowdstrike-falcon-sa` vs the documentation change. With the permissions we apply to the service accounts, it is better not to use `default`.

**Comment by falcon-pioupiou** [comment]
Actually falcon-operator is using the default service account AND in our official document (on falcon console) it's also default used.
and based on existing deployment it could be a breaking change for those who are using OIDC or Workload Identity

**Comment by falcon-pioupiou** [comment]
I've made the change last december to match crowdstrike-falcon-sa here : https://github.com/CrowdStrike/falcon-operator/pull/317 but unfortunately it's creating more issues because falcon-operator is using default and our internal doc is stating default as well (which is correct because operator is using default while helm is using crowdstrike-falcon-sa)

**Comment by jsullivan-CS** [comment]
I think @redhatrises is right -- the only case in which I can see it would matter, is the event in which a customer users the operator to deploy both the node and container sensors on the same cluster -- but in that case, it would provide the node sensor with permissions to read from GCR, which is unnecessary and thus should likely be changed (back) to a dedicated SA.  Thanks for the catch Gabe.
I'll discuss with a couple people internally to see if they have opinions on how to handle the break.

**Comment by redhatrises** [comment]
Closing this PR as setting the default serviceAccount is no longer allowed. Thanks for opening!

**Pull request closed without merging**
