### PR TITLE
Do no longer require user to provide CCID for Falcon Container

### PR DESCRIPTION
**Pull request by isimluk**

### CODE REVIEW

**Comment by isimluk** [comment]
Reworked to still allow users to pass in the CID.

**Comment by redhatrises** [comment]
@isimluk looks like the metadata sanity check has failed.

**Comment by isimluk** [comment]
Fixed & re-tested on cluster.

**Comment by isimluk** [comment]
@redhatrises, There is something weird going on with these CodeQL jobs.I just restarted it and watched it to successful completion, for some reason the successful completion is not reported back to the PR.

**Comment by isimluk** [comment]
CodeQL got unstuck.

**Comment by isimluk** [comment]
Green as it gets.

**Pull request merged**
