### PR TITLE
Fix vscode tools issue

### PR DESCRIPTION
**Pull request by redhatrises**
- Rename dockerfile.go to dockerfiles.go as vscode tools thinks that dockerfile.go is a dockerfile instead of a golang file

### CODE REVIEW

**Review by isimluk — CHANGES_REQUESTED** [review]
Wouldn't it be more appropriate to patch vscode?

**Comment by redhatrises** [comment]
> Wouldn't it be more appropriate to patch vscode?

I think that this is expected of the container tooling behavior to handle the dockerfile.rhel7, dockerfile.rhel8 file naming scenarios which can be quite common. So, I don't believe that a patch to vscode would happen or be accepted. Happy to be wrong.

**Comment by isimluk** [comment]
I am rather hesitant to change code just because some esoteric coding environment malfunctions on it. Feels wrong.

But you know what? I will accept it this as an exception. An exception to the rule. 

I don't do this often, @redhatrises.

asdf

**Review by isimluk — APPROVED** [review]
I hereby accept.

**Pull request merged**
