### PR TITLE
Initial CI for falcon-operator

### PR DESCRIPTION
**Pull request by isimluk**
At this stage we just make sure we can compile

### CODE REVIEW

**Comment by isimluk** [comment]
Please do not merge until we see this CI passing. Currently, this CI is not running as Github is experiencing service degradation.
```
Update - GitHub Actions is experiencing degraded performance. We are continuing to investigate.
Jan 19, 12:06 UTC
```

**Comment by shawndwells** [comment]
@isimluk showing a build service has not been setup:

image

**Comment by isimluk** [comment]
> @isimluk showing a build service has not been setup:
> 

I was under an assumption that this banner invites us to create a workflow like this one. I mean the banner just advocates we set-up some github action that builds the image. It doesn't feel related to the fact that there are no actions running on this pr.

**Comment by isimluk** [comment]
This pr was created at the time of github actions outage. It seems that I cannot get the CI run in this particular pr. I have opened the very same pr at #8 to force trigger the github actions.

**Pull request closed without merging**
