### PR TITLE
Fix OOMKilled issue on the clusters with huge configmaps

### PR DESCRIPTION
**Pull request by isimluk**

### CODE REVIEW

**Comment by domdepasquale** [comment]
FWIW, I believe this can happen for "very large" and "copious amounts of" secrets as well.

**Comment by isimluk** [comment]
Note: side effect of this change is that:
 - When user edits our daemonset's configmap nothing will happen
Previously, we would pick up the user edit of the configmap, and revert their edit in short moment.

**Comment by redhatrises** [comment]
This seems to consistently break on openshift deployments. Tested in separate clusters with separate users. I think that the desire is to keep this functionality vs removing it.

**Comment by isimluk** [comment]
> This seems to consistently break on openshift deployments. 

What exactly breaks?

**Comment by redhatrises** [comment]
> > This seems to consistently break on openshift deployments.
> 
> What exactly breaks?

OOM happens on CR deployment, so the OOM has shifted from operator install to resource deployment.

**Comment by domdepasquale** [comment]
Should we close this one @redhatrises @isimluk ?

**Pull request closed without merging**
